prompts = [
    "A librarian discovers a book that writes itself based on the reader's life.",
    "A time traveler accidentally brings a dinosaur to the present day.",
    "A musician realizes their songs can control the weather.",
    "A person wakes up with the ability to hear animals' thoughts.",
    "A small town where everyone has the same dream every night.",
    "A detective solves crimes by entering the memories of the deceased.",
    "A child finds a door in their closet that leads to a world of shadows.",
    "A scientist creates a device that can erase memories but accidentally uses it on themselves.",
    "A painter’s portraits come to life when no one is watching.",
    "A person receives a letter from their future self warning them of a terrible mistake.",
    "A town where it rains every time someone tells a lie.",
    "A person discovers their reflection has a mind of its own.",
    "A couple finds a map to a treasure hidden in their own backyard.",
    "A writer’s fictional characters start appearing in real life.",
    "A person wakes up to find they’ve switched bodies with their pet.",
    "A world where people can trade years of their life for wealth or talent.",
    "A photographer captures images of events that haven’t happened yet.",
    "A person discovers their family has been guarding a portal to another dimension.",
    "A town where everyone ages backward after turning 30.",
    "A person finds a necklace that grants them one wish per day.",
    "A group of friends discovers a hidden cave that freezes time inside.",
    "A person starts receiving text messages from a number that doesn’t exist.",
    "A world where emotions are visible as colors above people’s heads.",
    "A person inherits a house that changes its layout every night.",
    "A child’s imaginary friend becomes real and starts causing trouble.",
    "A person discovers they can communicate with the dead through old photographs.",
    "A town where everyone’s shadow has a different personality.",
    "A person finds a journal that writes their future as they live it.",
    "A world where everyone is born with a timer showing how long they’ll live.",
    "A person wakes up to find they’re the last person on Earth.",
    "A scientist creates a pill that erases fear but has unintended consequences.",
    "A person discovers their dreams are actually memories from another life.",
    "A town where every full moon, one person disappears without a trace.",
    "A person finds a mirror that shows their darkest secret.",
    "A world where people can only speak in riddles.",
    "A person discovers they can bring inanimate objects to life by drawing faces on them.",
    "A town where every resident has a doppelgänger living among them.",
    "A person finds a key that opens any door, even ones that don’t exist.",
    "A world where everyone’s age is determined by their wisdom, not time.",
    "A person discovers they can see the future but only five seconds at a time.",
    "A town where every night, the stars rearrange themselves to spell messages.",
    "A person finds a camera that captures images of parallel universes.",
    "A world where people can trade voices with others.",
    "A person discovers they can rewind time but only by 10 seconds.",
    "A town where every resident has a unique superpower, except for one person.",
    "A person finds a pen that writes stories that come true.",
    "A world where everyone is born with a tattoo that predicts their fate.",
    "A person discovers they can hear the thoughts of people in paintings.",
    "A town where every house is a different color, and the colors change based on the occupants’ moods.",
    "A person finds a clock that stops time but only for themselves.",
    "A world where people can only tell the truth on Tuesdays.",
    "A person discovers they can communicate with their past self through dreams.",
    "A town where every resident has a twin they’ve never met.",
    "A person finds a map that leads to a city hidden beneath the ocean.",
    "A world where everyone’s name determines their destiny.",
    "A person discovers they can see the memories of anyone they touch.",
    "A town where every resident is born with a unique symbol on their hand that glows when they meet their soulmate.",
    "A person finds a radio that broadcasts conversations from the future.",
    "A world where people can only sleep during the day and are awake at night.",
    "A person discovers they can turn invisible but only when no one is looking at them.",
    "A town where every tree grows a different type of fruit, regardless of the season.",
    "A person finds a pair of glasses that allow them to see people’s true intentions.",
    "A world where every word spoken aloud becomes a physical object.",
    "A person discovers they can teleport but only to places they’ve never been before.",
    "A town where every resident has a personal cloud that reflects their mood.",
    "A person finds a compass that points to whatever they desire most.",
    "A world where people can only communicate through written notes.",
    "A person discovers they can control plants but only when singing.",
    "A town where every resident has a unique scent that changes based on their emotions.",
    "A person finds a lantern that lights up only in the presence of danger.",
    "A world where everyone’s shadow moves independently and has its own personality.",
    "A person discovers they can speak to the wind and it answers back.",
    "A town where every resident has a clock that counts down to their most significant life event.",
    "A person finds a journal that writes itself with stories from alternate realities.",
    "A world where people can only see in black and white until they fall in love.",
    "A person discovers they can turn their drawings into reality but only for 24 hours.",
    "A town where every resident has a unique mark that glows when they’re near their greatest fear.",
    "A person finds a pair of shoes that allow them to walk on water.",
    "A world where every person’s voice has a unique magical effect.",
    "A person discovers they can see the history of any object they touch.",
    "A town where every resident has a personal star that shines brighter or dimmer based on their happiness.",
    "A person finds a mirror that shows them their life if they had made different choices.",
    "A world where people can only remember one day at a time.",
    "A person discovers they can control fire but only when they’re angry.",
    "A town where every resident has a unique melody that plays when they’re near.",
    "A person finds a book that contains every secret ever kept.",
    "A world where people can only see their own reflection in the eyes of others.",
    "A person discovers they can turn back time but only by one minute.",
    "A town where every resident has a personal guardian animal that only they can see.",
    "A person finds a map that leads to a place that doesn’t exist on any other map.",
    "A world where people can only speak in rhymes.",
    "A person discovers they can communicate with the moon and it responds.",
    "A town where every resident has a unique power that only works when they’re helping someone else.",
    "A person finds a key that unlocks any door, even ones that don’t exist.",
    "A world where people can only see the color of their true love’s eyes.",
    "A person discovers they can turn their thoughts into physical objects.",
    "A town where every resident has a personal raincloud that follows them everywhere.",
    "A person finds a journal that writes itself with stories from the future.",
    "A world where people can only hear the voices of those they truly care about.",
    "A person discovers they can control the tides but only during a full moon.",
    "A town where every resident has a unique mark that glows when they’re near their greatest joy.",
    "A person finds a pair of gloves that allow them to touch and manipulate memories.",
    "A world where people can only see their own shadow if they’re telling the truth.",
    "A person discovers they can turn into any animal but only for one hour a day.",
    "A town where every resident has a personal constellation that changes based on their life events.",
    "A person finds a mirror that shows them their life if they had taken a different path.",
    "A world where people can only dream about the future.",
    "A person discovers they can control the wind but only when they’re calm.",
    "A town where every resident has a unique scent that changes based on their mood.",
    "A person finds a compass that points to their greatest fear.",
    "A world where people can only see the true colors of things when they’re happy.",
    "A person discovers they can turn their thoughts into music.",
    "A town where every resident has a personal star that guides them through life.",
    "A person finds a book that contains every story ever told.",
    "A world where people can only see their reflection in the eyes of those who love them.",
    "A person discovers they can turn back time but only by one second.",
    "A town where every resident has a unique melody that plays when they’re near their soulmate.",
    "A person finds a key that unlocks any door, even ones that don’t exist.",
    "A world where people can only see the color of their true love’s eyes.",
    "A person discovers they can turn their thoughts into physical objects.",
    "A town where every resident has a personal raincloud that follows them everywhere.",
    "A person finds a journal that writes itself with stories from the future.",
    "A world where people can only hear the voices of those they truly care about.",
    "A person discovers they can control the tides but only during a full moon.",
    "A town where every resident has a unique mark that glows when they’re near their greatest joy.",
    "A person finds a pair of gloves that allow them to touch and manipulate memories.",
    "A world where people can only see their own shadow if they’re telling the truth.",
    "A person discovers they can turn into any animal but only for one hour a day.",
    "A town where every resident has a personal constellation that changes based on their life events.",
    "A person finds a mirror that shows them their life if they had taken a different path.",
    "A world where people can only dream about the future.",
    "A person discovers they can control the wind but only when they’re calm.",
    "A town where every resident has a unique scent that changes based on their mood.",
    "A person finds a compass that points to their greatest fear.",
    "A world where people can only see the true colors of things when they’re happy.",
    "A person discovers they can turn their thoughts into music.",
    "A town where every resident has a personal star that guides them through life.",
    "A person finds a book that contains every story ever told.",
    "A world where people can only see their reflection in the eyes of those who love them.",
    "A person discovers they can turn back time but only by one second.",
    "A town where every resident has a unique melody that plays when they’re near their soulmate."
]